apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: restaurant-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017
        volumeMounts:
        - mountPath: /data/db
          name: mongo-data
      volumes:
      - name: mongo-data
        emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: restaurant-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: affanwajid/backend:latest   
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: "mongodb://mongo-service:27017/restaurant-db"
        - name: PORT
          value: "5000"
        - name: JWT_SECRET
          value: "my_secret_key"
        - name: JWT_EXPIRES_IN
          value: "30d"
        - name: ORIGIN
          value: "http://frontend-service:80"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: restaurant-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: affanwajid/frontend:latest
        ports:
        - containerPort: 80
        env:
        - name: VITE_API_URL
          value: "http://backend-service:5000/api"