name: Build & Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Docker to use Minikube's daemon
        shell: powershell
        run: |
          Write-Host "Switching to Minikube Docker..."
          $envs = & minikube -p minikube docker-env --shell powershell | Out-String
          Invoke-Expression $envs

      - name: Build backend image
        working-directory: resturant-backend-main
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:latest .

      - name: Build frontend image
        working-directory: resturant-frontend-main
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}



      - name: Push backend image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest

      - name: Push frontend image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest

      - name: Deploy to Minikube
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
