name: Build & Deploy to Minikube


on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Docker to use Minikube's daemon
        shell: powershell
        run: |
          Write-Host "Switching to Minikube Docker..."
          & minikube -p minikube docker-env --shell=cmd | Invoke-Expression

      - name: Build backend image
        working-directory: resturant-backend-main
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:latest .

      - name: Build frontend image
        working-directory: resturant-frontend-main
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest .

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | \
            docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push backend image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest

      - name: Push frontend image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest

      - name: Deploy to Minikube
        env:
          KUBECONFIG: ${{ github.workspace }}/.kube/config
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
